Update convert.yml

diff --git a/.github/workflows/convert.yml b/.github/workflows/convert.yml
--- a/.github/workflows/convert.yml
+++ b/.github/workflows/convert.yml
@@ -38,6 +38,9 @@ jobs:
       - name: Run convert-host.py
         run: python3 sumber/convert-host.py || { echo 'convert-host.py failed'; exit 1; }
 
+      - name: Run convert-ub.py
+        run: python3 sumber/convert-ub.py || { echo 'convert-host.py failed'; exit 1; }
+
       - name: Run convert.py
         run: python3 sumber/convert.py || { echo 'convert.py failed'; exit 1; }
 
