Update convert.yml

diff --git a/.github/workflows/convert.yml b/.github/workflows/convert.yml
--- a/.github/workflows/convert.yml
+++ b/.github/workflows/convert.yml
@@ -39,10 +39,10 @@ jobs:
         run: python3 sumber/convert-host.py || { echo 'convert-host.py failed'; exit 1; }
 
       - name: Run convert-ub.py
-        run: python3 sumber/convert-ub.py || { echo 'convert-host.py failed'; exit 1; }
+        run: python3 sumber/convert-ub.py || { echo 'convert-ub.py failed'; exit 1; }
 
       - name: Run convert-json.py
-        run: python3 sumber/convert-json.py || { echo 'convert-host.py failed'; exit 1; }
+        run: python3 sumber/convert-json.py || { echo 'convert-json.py failed'; exit 1; }
 
       - name: Run convert.py
         run: python3 sumber/convert.py || { echo 'convert.py failed'; exit 1; }
